version: 2
jobs:
  build-job:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:setup
      - run: bundle exec rake graydb:import
      - run:
          name: Run tests
          command: bundle exec rake test

  deploy-job:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec cap production deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: production
