version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:setup
      - run: bundle exec rake graydb:import
  test:
    docker:
      - image: circleci/ruby:2.4-node
    steps:
      - checkout
      - run:
        name: Run tests
        command: rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
#  build-test-and-deploy:
#    jobs:
#      - build
#      - test:
#        requires:
#          - build
#        context: org-global
#      - deploy:
#        requires:
#          - test
#        filters:
#          branches:
#            only: production
