version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
        environment:
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rails db:setup
      - run: bundle exec rake graydb:import
      - run:
          name: Run tests
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
#  build-test-and-deploy:
#    jobs:
#      - build
#      - test:
#        requires:
#          - build
#        context: org-global
#      - deploy:
#        requires:
#          - test
#        filters:
#          branches:
#            only: production
